CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers(
    id INTEGER(11) AUTO_INCREMENT NOT NULL,
    burger_name VARCHAR(500) NOT NULL,
    devoured TINYINT(1) DEFAULT 0,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);